version: '2'
services:
  web:
    build: php-apache
    ports:
      - "80:80"
    volumes:
      - "/home/thetys/PhpstormProjects/quizz:/var/www/html"
    links:
      - db
  db:
    image: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quizz
      - MYSQL_USER=quizz
      - MYSQL_PASSWORD=quizz
    volumes:
      - "./mariadb/datadir:/var/lib/mysql"
